"""The allowlist evaluator, pinned to the proxy's own decision vectors.

The rules and expected verdicts below are copied verbatim from
``apps/proxy/testdata/policy-vectors.json`` — the fixture generated by the real
``@seekrit/core`` evaluator and asserted by ``crates/seekrit-core``. Keeping them
here means a glob or precedence change in one implementation shows up as a
failure in the other two, without a fifth copy of a synced fixture.

Runnable with either ``pytest`` or ``python -m unittest``.
"""

import unittest

from seekrit._policy import AllowRule, evaluate, match_path, narrow, rules_from_allow

RULES = [
    AllowRule(
        host="api.openai.com",
        methods=("POST",),
        paths=("/v1/chat/completions", "/v1/embeddings"),
        allow=("OPENAI_API_KEY",),
        label="chat + embeddings",
    ),
    AllowRule(
        host="api.openai.com",
        methods=("GET",),
        paths=("/v1/models", "/v1/models/*"),
        allow=(),
    ),
    AllowRule(
        host="api.github.com",
        methods=("GET", "POST"),
        paths=("/repos/*/issues", "/repos/*/issues/**"),
        allow=("GITHUB_TOKEN",),
    ),
    AllowRule(host="hooks.slack.com", allow=("SLACK_WEBHOOK_URL",)),
]

# (host, method, path, secret, decision, rule_index)
DECISIONS = [
    ("api.openai.com", "POST", "/v1/chat/completions", "OPENAI_API_KEY", "allow", 0),
    ("api.openai.com", "POST", "/v1/chat/completions?stream=true", None, "allow", 0),
    ("api.openai.com", "POST", "/v1/chat/completions", "GITHUB_TOKEN", "secret_not_allowed", 0),
    ("api.openai.com", "GET", "/v1/models", None, "allow", 1),
    ("api.openai.com", "GET", "/v1/models/gpt-9", "OPENAI_API_KEY", "secret_not_allowed", 1),
    ("api.openai.com", "DELETE", "/v1/models", None, "method_not_allowed", 1),
    ("api.openai.com", "POST", "/v1/files", None, "path_not_allowed", None),
    ("api.github.com", "POST", "/repos/seekrit/issues", "GITHUB_TOKEN", "allow", 2),
    ("api.github.com", "POST", "/repos/seekrit/issues/12/comments", "GITHUB_TOKEN", "allow", 2),
    ("api.github.com", "POST", "/repos/a/b/issues", None, "path_not_allowed", None),
    ("api.github.com", "PATCH", "/repos/seekrit/issues", None, "method_not_allowed", 2),
    ("hooks.slack.com", "POST", "/services/T0/B0/xyz", "SLACK_WEBHOOK_URL", "allow", 3),
    ("evil.example.com", "POST", "/", "OPENAI_API_KEY", "no_rule", None),
]


class PolicyDecisionTests(unittest.TestCase):
    def test_matches_the_proxy_decision_vectors(self):
        for host, method, path, secret, decision, rule_index in DECISIONS:
            with self.subTest(f"{method} {host}{path} {secret or '-'}"):
                verdict = evaluate(RULES, host=host, method=method, path=path, secret=secret)
                self.assertEqual(verdict.decision, decision)
                self.assertEqual(verdict.rule_index, rule_index)

    def test_host_and_method_matching_is_case_insensitive(self):
        verdict = evaluate(
            RULES, host="API.OpenAI.com", method="post", path="/v1/embeddings",
            secret="OPENAI_API_KEY",
        )
        self.assertEqual(verdict.decision, "allow")

    def test_the_query_string_never_participates_in_path_matching(self):
        self.assertTrue(match_path("/v1/models", "/v1/models?limit=1"))

    def test_double_star_covers_zero_segments(self):
        self.assertTrue(match_path("/v1/**", "/v1"))
        self.assertTrue(match_path("/v1/**", "/v1/a/b/c"))

    def test_single_star_does_not_cross_a_segment(self):
        self.assertTrue(match_path("/repos/*/issues", "/repos/one/issues"))
        self.assertFalse(match_path("/repos/*/issues", "/repos/one/two/issues"))


class ShorthandTests(unittest.TestCase):
    def test_shorthand_permits_any_operation_toward_that_host(self):
        rules = rules_from_allow({"api.openai.com": ["OPENAI_API_KEY"]})
        for method, path in (("POST", "/v1/chat/completions"), ("GET", "/anything")):
            verdict = evaluate(
                rules, host="api.openai.com", method=method, path=path, secret="OPENAI_API_KEY"
            )
            self.assertEqual(verdict.decision, "allow")

    def test_an_empty_allow_list_denies_every_secret(self):
        rules = rules_from_allow({"api.openai.com": []})
        verdict = evaluate(
            rules, host="api.openai.com", method="POST", path="/v1/x", secret="OPENAI_API_KEY"
        )
        self.assertEqual(verdict.decision, "secret_not_allowed")


class NarrowingTests(unittest.TestCase):
    def test_narrowing_intersects_and_never_widens(self):
        narrowed = narrow(RULES, ["OPENAI_API_KEY", "NEVER_PERMITTED"])
        self.assertEqual(narrowed[0].allow, ("OPENAI_API_KEY",))
        self.assertEqual(narrowed[2].allow, ())  # GITHUB_TOKEN dropped
        for rule in narrowed:
            self.assertNotIn("NEVER_PERMITTED", rule.allow)

    def test_narrowing_preserves_the_operation_constraints(self):
        narrowed = narrow(RULES, ["OPENAI_API_KEY"])
        self.assertEqual(narrowed[0].methods, ("POST",))
        self.assertEqual(narrowed[0].paths, ("/v1/chat/completions", "/v1/embeddings"))


class FromDictTests(unittest.TestCase):
    def test_reads_a_bundle_rule_verbatim(self):
        rule = AllowRule.from_dict(
            {
                "host": "api.github.com",
                "methods": ["GET", "POST"],
                "paths": ["/repos/*/issues"],
                "allow": ["GITHUB_TOKEN"],
                "label": "issues",
            }
        )
        self.assertEqual(rule.host, "api.github.com")
        self.assertEqual(rule.methods, ("GET", "POST"))
        self.assertEqual(rule.allow, ("GITHUB_TOKEN",))

    def test_missing_lists_default_to_empty(self):
        rule = AllowRule.from_dict({"host": "example.com"})
        self.assertEqual((rule.methods, rule.paths, rule.allow), ((), (), ()))


if __name__ == "__main__":
    unittest.main()
